services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TRAW\ListViewExt\:
    resource: '../Classes/*'

  TRAW\ListViewExt\Hooks\ListViewPostProcessor:
    public: true
